
name: Connectify - Front

on:

  push:
    branches: [ "dev_test" ]

  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: GIT | Checkout
      uses: actions/checkout@v4

    - name: GIT | Get current branch
      run: echo "CURRENT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: DOCKER | Login, Build and PUSH
      env:
        ACR: atcdevacr.azurecr.io
        ACR_SUFFIX: azurecr.io
        IMG_NAME: connectify-front 
      run: |
        
        echo "DOCKER | Azure docker login"
        az acr login --name $ACR

    
        $IMG = $ACR/$IMG_NAME-$env.CURRENT_BRANCH

        echo "DOCKER | Build Image"
        docker build -t $IMG .
        docker push $IMG 

 
