name: Build and Push to ACR

on:
  push:
    branches:
      - main  # Adjust branch as needed

permissions:
  id-token: write  # Needed for OIDC login
  contents: read  # Read repo contents

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true  # Needed if federated identity is tied to a resource, not a subscription

      - name: Log in to Azure Container Registry
        run: az acr login --name myregistry

      - name: Build and tag Docker image
        run: |
          docker build -t atcdevacr.azurecr.io/connectify-front-dev .
      
      - name: Push image to ACR
        run: |
          docker push atcdevacr.azurecr.io/connectify-front-dev
