name: Connectify - Front

on:
  push:
    branches: [ "dev_test" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: GIT | Get current branch
        run: echo "CURRENT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: AZURE | CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Example Azure CLI Command
        run: |
          echo "Executing az account show"
          az account show

      - name: DOCKER | Login, Build and Push
        env:
          ACR: atcdevacr.azurecr.io
          IMG_NAME: connectify-front
        run: |
          az login --identity --username $secrets.AZURE_CLIENT_ID
          az acr login --name $ACR

          IMG=$ACR/$IMG_NAME-$CURRENT_BRANCH

          echo "DOCKER | Build Image"
          docker build -t $IMG .

          echo "DOCKER | Push Image"
          docker push $IMG
